---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: otel-collector
          static_configs:
            - targets:
                - "localhost:8888"
              labels:
                job_name: otel-collector
        - job_name: "growth-app"
          scrape_interval: 5s
          static_configs:
            - targets:
                - "growth:4000"
              labels:
                job_name: "growth-app"

  syslog:
    tcp:
      listen_address: "0.0.0.0:5140"
    protocol: rfc5424
    location: UTC
    operators:
      - type: move
        from: attributes.message
        to: body

processors:
  batch:
    send_batch_size: 10240
    send_batch_max_size: 20480
    timeout: 15s

  memory_limiter:
    check_interval: 10s
    limit_mib: 512
    spike_limit_mib: 256

  resourcedetection:
    detectors: [env, system]
    timeout: 5s

  signozspanmetrics/delta:
    metrics_exporter: signozclickhousemetrics
    metrics_flush_interval: 60s
    latency_histogram_buckets:
      [
        100us,
        1ms,
        2ms,
        6ms,
        10ms,
        50ms,
        100ms,
        250ms,
        500ms,
        1000ms,
        1400ms,
        2000ms,
        5s,
        10s,
        20s,
        40s,
        60s,
      ]
    dimensions_cache_size: 100000
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    enable_exp_histogram: true
    dimensions:
      - name: service.namespace
        default: default
      - name: deployment.environment
        default: default
      - name: signoz.collector.id
      - name: service.version
      - name: browser.platform
      - name: browser.mobile
      - name: host.name
      - name: host.type
      - name: container.name

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1777"

exporters:
  # Debug exporter for local development
  debug:
    verbosity: detailed

  clickhouselogsexporter:
    dsn: "tcp://clickhouse:9000/signoz_logs"
    timeout: 10s
    use_new_schema: true

  clickhousetraces:
    datasource: "tcp://clickhouse:9000/signoz_traces"
    low_cardinal_exception_grouping: "${env:LOW_CARDINAL_EXCEPTION_GROUPING}"
    use_new_schema: true

  signozclickhousemetrics:
    dsn: "tcp://clickhouse:9000/signoz_metrics"

service:
  telemetry:
    logs:
      encoding: json

  extensions:
    - health_check
    - pprof

  pipelines:
    logs:
      receivers: [otlp, syslog]
      processors: [memory_limiter, batch]
      exporters: [clickhouselogsexporter, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [signozclickhousemetrics, debug]

    metrics/prometheus:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [signozclickhousemetrics, debug]

    traces:
      receivers: [otlp]
      processors: [signozspanmetrics/delta, memory_limiter, batch]
      exporters: [clickhousetraces, debug]
