---
name: ${GROWTH_PROJECT_NAME:-growth}

include:
  - path: ./priv/docker/services/observability/docker-compose.yml

services:
  growth:
    image: "anadubas/growth:${GROWTH_TAG:-dev}"
    build: .
    pull_policy: never
    init: true
    hostname: growth
    restart: unless-stopped
    develop:
      watch:
        - path: ./
          action: rebuild
    ports:
      - "${GROWTH_PORT:-:4000}"
    environment:
      SECRET_KEY_BASE: "${GROWTH_SECRET_KEY_BASE:-mVrA1wyJvtAVp0hIgT2DnZMfyWh5dPltmEUWYVXN2yp8O742eTeL7sEe4NH9pskF}"
      PHX_HOST: "${GROWTH_PHX_HOST:-127.0.0.1}"
      PHX_PORT: "${GROWTH_PHX_PORT:-4000}"
      PHX_SCHEME: "${GROWTH_PHX_SCHEME:-http}"
      RELEASE_DISTRIBUTION: name
    labels:
      "growth.scrape": "true"
      "growth.port": 4000
      "growth.path": /metrics

  live:
    image: "ghcr.io/livebook-dev/livebook:0.17.2"
    init: true
    hostname: live
    restart: unless-stopped
    ports:
      - "${LIVE_PORT:-:8080}"
    environment:
      LIVEBOOK_PASSWORD: "${LIVEBOOK_PASSWORD:-some_salt}"
      LIVEBOOK_COOKIE: "${LIVEBOOK_COOKIE:-some_cookie}"
      LIVEBOOK_NODE: "${LIVEBOOK_NODE:-live}"
      LIVEBOOK_SECRET_KEY_BASE: "${LIVEBOOK_SECRET_KEY_BASE:-some_key_base}"
      LIVEBOOK_HOME: /data
    volumes:
      - "live_data:/data"

volumes:
  live_data: {}
