---
name: ${GROWTH_PROJECT_NAME:-growth}

services:
  growth:
    image: 'anadubas/growth:${GROWTH_TAG:-dev}'
    build: .
    pull_policy: never
    init: true
    hostname: growth
    restart: unless-stopped
    develop:
      watch:
        - path: ./
          action: rebuild
    environment:
      SECRET_KEY_BASE: '${GROWTH_SECRET_KEY_BASE:-mVrA1wyJvtAVp0hIgT2DnZMfyWh5dPltmEUWYVXN2yp8O742eTeL7sEe4NH9pskF}'
      PHX_HOST: '${GROWTH_PHX_HOST:-127.0.0.1}'
      PHX_PORT: '${GROWTH_PHX_PORT:-4000}'
      PHX_SCHEME: '${GROWTH_PHX_SCHEME:-http}'
