---
version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:application:
    desc: "Compile the application"
    cmds:
      - mix compile --force --warnings-as-errors

  build:assets:
    desc: "Build assets"
    cmds:
      - mix assets.build

  build:
    desc: "Build the application and assets"
    cmds:
      - task: build:assets
      - task: build:application

  setup:
    desc: "Install dependencies and compile the application"
    cmds:
      - task: clean
      - task: deps
      - task: build

  clean:
    desc: "Clean build and deps"
    cmds:
      - mix do deps.clean --all, clean
      - MIX_ENV=test mix do deps.clean --all, clean
      - rm -rf assets/node_modules

  check:format:
    desc: "Check if the code is formatted"
    cmds:
      - mix format --check-formatted

  check:credo:
    desc: "Check if the code follows the Credo rules"
    cmds:
      - mix credo --strict

  check:dialyzer:
    desc: "Check if the code is linted"
    cmds:
      - mix dialyzer --format github --format dialyxir

  create_plt:
    desc: "Create PLT for dialyzer"
    cmds:
      - mix dialyzer --plt

  deps:application:
    desc: "Install elixir dependencies"
    cmds:
      - mix do deps.get, deps.compile

  deps:assets:
    desc: "Install node dependencies"
    cmds:
      - npm install --prefix ./assets

  deps:outdated:
    desc: "Check for outdated dependencies"
    cmds:
      - mix hex.outdated
      - npm outdated --prefix ./assets --all

  deps:
    desc: "Install application/assets dependencies"
    cmds:
      - task: deps:application
      - task: deps:assets

  lint:
    desc: "Run all linters"
    deps:
      - build:application
    cmds:
      - task: check:format
      - task: check:credo
      - task: check:dialyzer

  bootstrap:
    desc: "Add rebar and hex"
    cmds:
      - mix do local.hex --force, local.rebar --force

  test:
    desc: "Run all tests"
    cmds:
      - mix test --trace

  test:single:
    desc: "Run a single test file or test at specific line"
    cmds:
      - mix test {{.CLI_ARGS}}

  format:
    desc: "Format the code"
    cmds:
      - mix format

  server:
    desc: "Start the Phoenix server"
    cmds:
      - mix phx.server

  ci:
    desc: "Run all checks (equivalent to mix ci)"
    deps:
      - create_plt
    cmds:
      - task: lint
      - task: test
