defmodule Growth.AnthroCrossValidationTest do
  @moduledoc """
  Cross-validates the app's z-score calculations against the WHO's own
  reference implementation, the R `anthro` package
  (https://github.com/WorldHealthOrganization/anthro).

  The golden fixture `test/fixtures/anthro_golden.csv` is generated by
  `test/fixtures/generate_anthro_golden.R`, which runs WHO's reference
  implementation over a grid of (gender × age × indicator × z-score target) and
  records:

    * the WHO day-table LMS values used (`lms_l`, `lms_m`, `lms_s`),
    * the measure value that produces the target z-score,
    * the reference z-score (`expected_z`, rounded to 2 decimals by R).

  Each fixture row is asserted twice:

    1. *Formula equivalence* — `Growth.Zscore.calculate/4` fed with the WHO
       day-table LMS values must reproduce `expected_z`. This validates the
       LMS math, including the WHO adjustment beyond ±3 SD, in isolation.
    2. *End-to-end pipeline* — `Growth.Calculate.calculate_result/3` (the
       app's own month-indexed reference tables, age derivation and lookup)
       must reproduce `expected_z`.

  The pipeline comparison has a looser tolerance because the app resolves
  reference rows by whole months while the reference implementation uses day
  precision. Fixture ages sit on `ceiling(k * 30.4375)` so the two resolve
  to reference points at most one day apart on the underlying WHO curves;
  the remaining drift is measurement noise from table granularity, not an
  error. If this test fails with drift well above the tolerance, suspect a
  data or lookup regression in `Growth.CSVLoader` / `Growth.LoadReference`.

  Fixture ages cover months 0..59. Beyond 60 months the WHO reference
  implementation returns NA, so ages >= 5 years cannot be validated against
  it (the app's 5+ tables come from the WHO 2007 reference, a different
  dataset).
  """

  use ExUnit.Case, async: true

  alias Growth.{Calculate, Child, Zscore}

  @fixture_path Path.join([__DIR__, "..", "fixtures", "anthro_golden.csv"])
  @measure_date ~D[2024-06-15]

  # expected_z is rounded to 2 decimals by the reference implementation.
  @formula_tolerance 0.011

  # Drift allowed between the app's month-indexed tables and R's day-indexed
  # tables. Fixture ages align the two within one day on the WHO curves, so
  # the observed drift is growth over that day, largest in early infancy.
  # Measured max drift per indicator: bmi 0.036, head_circumference 0.036,
  # height 0.042, weight 0.043. 0.15 leaves headroom while still failing on
  # real regressions (wrong table rows, off-by-one-month lookups, data
  # transcription errors all drift far beyond it).
  @pipeline_tolerance 0.15

  @indicators [:weight, :height, :bmi, :head_circumference]

  setup_all do
    rows =
      @fixture_path
      |> File.read!()
      |> NimbleCSV.RFC4180.parse_string(skip_headers: true)
      |> Enum.map(fn [
                       gender,
                       age_in_days,
                       age_in_months,
                       indicator,
                       lms_l,
                       lms_m,
                       lms_s,
                       measure,
                       weight_kg,
                       height_cm,
                       expected_z
                     ] ->
        %{
          gender: gender,
          age_in_days: String.to_integer(age_in_days),
          age_in_months: String.to_integer(age_in_months),
          indicator: String.to_existing_atom(indicator),
          lms: {parse_single(lms_l), parse_single(lms_m), parse_single(lms_s)},
          measure: parse_single(measure),
          weight_kg: parse_single(weight_kg),
          height_cm: parse_single(height_cm),
          expected_z: parse_single(expected_z)
        }
      end)

    assert rows != [], "fixture #{@fixture_path} is empty"
    %{rows: rows}
  end

  for indicator <- @indicators do
    test "LMS formula reproduces WHO anthro reference for #{indicator}", %{rows: rows} do
      rows = Enum.filter(rows, &(&1.indicator == unquote(indicator)))

      {failures, max_drift} =
        drift_stats(rows, @formula_tolerance, fn row ->
          {l, m, s} = row.lms
          Zscore.calculate(row.measure, l, m, s)
        end)

      assert Enum.empty?(failures), failure_message(rows, failures, max_drift, @formula_tolerance)
    end

    test "pipeline reproduces WHO anthro reference for #{indicator}", %{rows: rows} do
      rows = Enum.filter(rows, &(&1.indicator == unquote(indicator)))

      {failures, max_drift} =
        drift_stats(rows, @pipeline_tolerance, fn row ->
          child = build_child(row)
          result = Calculate.calculate_result(measure_value(row), unquote(indicator), child)
          assert result.available?, "no reference result for #{describe_row(row)}"
          result.zscore
        end)

      assert Enum.empty?(failures),
             failure_message(rows, failures, max_drift, @pipeline_tolerance)
    end
  end

  defp drift_stats(rows, tolerance, zscore_fun) do
    {failures, max_drift} =
      Enum.reduce(rows, {[], 0.0}, fn row, {failures, max_drift} ->
        zscore = zscore_fun.(row)
        drift = abs(zscore - row.expected_z)

        failures =
          if drift > tolerance do
            [{row, zscore, drift} | failures]
          else
            failures
          end

        {failures, max(drift, max_drift)}
      end)

    {Enum.reverse(failures), max_drift}
  end

  defp measure_value(%{indicator: :bmi} = row), do: Calculate.bmi(row.weight_kg, row.height_cm)
  defp measure_value(row), do: row.measure

  defp build_child(%{gender: gender, age_in_days: age_in_days}) do
    birthday = Date.add(@measure_date, -age_in_days)

    %Child{
      name: "cross-validation",
      gender: gender,
      birthday: birthday,
      measure_date: @measure_date,
      age_in_months: Calculate.age_in_months(birthday, @measure_date),
      age_in_decimal: Calculate.in_months_decimal(birthday, @measure_date)
    }
  end

  defp failure_message(all_rows, failures, max_drift, tolerance) do
    worst =
      failures
      |> Enum.sort_by(fn {_row, _zscore, drift} -> drift end, :desc)
      |> Enum.take(8)
      |> Enum.map_join("\n", fn {row, zscore, drift} ->
        "  #{describe_row(row)}: expected #{row.expected_z}, got #{zscore} (drift #{Float.round(drift, 4)})"
      end)

    """
    #{length(failures)} of #{length(all_rows)} rows exceed drift tolerance #{tolerance} (max drift #{Float.round(max_drift, 4)}). Worst offenders:
    #{worst}
    """
  end

  defp describe_row(row) do
    "#{row.gender} day=#{row.age_in_days} (month=#{row.age_in_months}) #{row.indicator}=#{row.measure}"
  end

  defp parse_single(value) do
    case Float.parse(value) do
      {number, _rest} -> number
      :error -> nil
    end
  end
end
