---
name: Continuous Integration Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  deps:
    name: Fetch dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup erlang/elixir/taskfile runtimes
        uses: jdx/mise-action@v2
      - name: Prepare system
        run: task prepare_system
      - name: Cache dependencies and compiled build
        id: cache-deps
        uses: actions/cache@v4
        env:
          CACHE_NAME: cache-elixir-deps-and-build
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-
      - name: Clean up to avoid incremental build as source of flakiness
        if: github.run_attempt != '1'
        run: mix do deps.clean --all, clean
        shell: sh
      - name: Install dependencies
        run: task deps
      - name: Compile without warnings
        run: task build

  format:
    name: Check code format
    runs-on: ubuntu-24.04
    needs:
      - deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup erlang/elixir/taskfile runtimes
        uses: jdx/mise-action@v2
      - name: Prepare system
        run: task prepare_system
      - name: Restore deps/compiled build from cache
        id: cache-deps
        uses: actions/cache/restore@v4
        env:
          CACHE_NAME: cache-elixir-deps-and-build
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-
      - name: Check
        run: task check_format

  credo:
    name: Check credo lint
    runs-on: ubuntu-24.04
    needs: deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup erlang/elixir/taskfile runtimes
        uses: jdx/mise-action@v2
      - name: Prepare system
        run: task prepare_system
      - name: Restore deps/compiled build from cache
        id: cache-deps
        uses: actions/cache/restore@v4
        env:
          CACHE_NAME: cache-elixir-deps-and-build
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-
      - name: Check
        run: task check_credo

  dialyzer:
    name: Check dialyzer
    runs-on: ubuntu-24.04
    needs: deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup erlang/elixir/taskfile runtimes
        uses: jdx/mise-action@v2
      - name: Prepare system
        run: task prepare_system
      - name: Restore deps/compiled build from cache
        id: cache-deps
        uses: actions/cache/restore@v4
        env:
          CACHE_NAME: cache-elixir-deps-and-build
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-
      - name: Restore PLT resource from cache
        id: cache-plt-restore
        uses: actions/cache/restore@v4
        env:
          CACHE_NAME: cache-plt
        with:
          path: priv/plts
          key: ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-
      - name: Clean up to avoida incremental build as source of flakiness
        if: github.run_attempt != '1'
        run: rm -rf priv/plts/*
      - name: Compile without warnings
        run: task build
      - name: Create PLTs
        run: task create_plt
      - name: Save PLT resource into cache
        id: cache-plt-save
        uses: actions/cache/save@v4
        env:
          CACHE_NAME: cache-plt
        with:
          path: priv/plts
          key: ${{ runner.os }}-mix-${{ env.CACHE_NAME }}-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
      - name: Check
        run: task check_dialyzer
